// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGMC.Persistence.Context;

#nullable disable

namespace SGMC.Persistence.Migrations
{
    [DbContext(typeof(HealtSyncContext))]
    [Migration("20260608235927_AddPasswordResetTokens")]
    partial class AddPasswordResetTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGMC.Domain.Entities.Appointments.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__Appointme__Creat__5165187F");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__Appointme__Updat__52593CB8");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCA291B4E736");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StatusId");

                    b.ToTable("Appointments", "appointments");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Appointments.DoctorAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AvailabilityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<DateOnly>("AvailableDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AvailabilityId")
                        .HasName("PK__DoctorAv__DA397991EEC28676");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailability", "appointments");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Insurance.InsuranceProvider", b =>
                {
                    b.Property<int>("InsuranceProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InsuranceProviderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceProviderId"));

                    b.Property<string>("AcceptedRegions")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CoverageDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__Insurance__Creat__2CF2ADDF");

                    b.Property<string>("CustomerSupportContact")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__Insurance__IsAct__2DE6D218");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__Insurance__IsPre__2BFE89A6");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("MaxCoverageAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NetworkTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("InsuranceProviderId");

                    b.HasIndex("NetworkTypeId");

                    b.ToTable("InsuranceProviders", "Insurance");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Insurance.NetworkType", b =>
                {
                    b.Property<int>("NetworkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NetworkTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__NetworkTy__Creat__29221CFB");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__NetworkTy__IsAct__2A164134");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("NetworkTypeId")
                        .HasName("PK__NetworkT__C09029EE538D704E");

                    b.ToTable("NetworkType", "Insurance");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Medical.AvailabilityMode", b =>
                {
                    b.Property<short>("AvailabilityModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("AvailabilityModeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("AvailabilityModeId"));

                    b.Property<string>("AvailabilityMode1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("AvailabilityMode");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_AvailabilityModes_CreatedAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_AvailabilityModes_IsActive");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_AvailabilityModes_UpdatedAt");

                    b.HasKey("AvailabilityModeId")
                        .HasName("PK__Availabi__A1FC32EB96F7E6BB");

                    b.HasIndex(new[] { "AvailabilityMode1" }, "UQ__Availabi__8598C8508EE645A1")
                        .IsUnique();

                    b.ToTable("AvailabilityModes", "medical");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Medical.MedicalRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__MedicalRe__Creat__5CD6CB2B");

                    b.Property<DateTime>("DateOfVisit")
                        .HasColumnType("datetime");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__MedicalRe__Updat__5DCAEF64");

                    b.HasKey("RecordId")
                        .HasName("PK__MedicalR__FBDF78C96E650FFC");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords", "medical");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Medical.Specialty", b =>
                {
                    b.Property<short>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("SpecialtyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("SpecialtyId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Specialties_CreatedAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Specialties_IsActive");

                    b.Property<string>("SpecialtyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Specialties_UpdatedAt");

                    b.HasKey("SpecialtyId")
                        .HasName("PK__Specialt__D768F648D93CE967");

                    b.HasIndex(new[] { "SpecialtyName" }, "UQ__Specialt__7DCA574800EB0679")
                        .IsUnique();

                    b.ToTable("Specialties", "medical");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.System.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E327D8F016B");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", "system");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.System.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Roles_CreatedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Roles_IsActive");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Roles_UpdatedAt");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A0AF7665C");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B61603EE5AFD9")
                        .IsUnique();

                    b.ToTable("Roles", "system");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.System.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__Status__C8EE2043759308C1");

                    b.HasIndex(new[] { "StatusName" }, "UQ__Status__05E7698AD7258224")
                        .IsUnique();

                    b.ToTable("Status", "system");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<short?>("AvailabilityModeId")
                        .HasColumnType("smallint");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("ConsultationFee")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Doctors_CreatedAt");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Doctors_IsActive");

                    b.Property<DateOnly>("LicenseExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<short>("SpecialtyId")
                        .HasColumnType("smallint")
                        .HasColumnName("SpecialtyID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("DoctorId")
                        .HasName("PK__Doctors__2DC00EDFCF31D9E9");

                    b.HasIndex("AvailabilityModeId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctors", "users");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04F11D75E95E5");

                    b.ToTable("Employees", "users");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", "users");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Patients_CreatedAt");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int>("InsuranceProviderId")
                        .HasColumnType("int")
                        .HasColumnName("InsuranceProviderID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Patients_IsActive");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("PatientId")
                        .HasName("PK__Patients__970EC346B158B7FB");

                    b.HasIndex("InsuranceProviderId");

                    b.ToTable("Patients", "users");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PersonID");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PersonId")
                        .HasName("PK__Persons__AA2FFB85C91EBDF7");

                    b.ToTable("Persons", "users");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Password");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACD6E62048");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534B973B1BC")
                        .IsUnique();

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Appointments.Appointment", b =>
                {
                    b.HasOne("SGMC.Domain.Entities.Users.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_Doctor");

                    b.HasOne("SGMC.Domain.Entities.Users.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_Patient");

                    b.HasOne("SGMC.Domain.Entities.System.Status", "Status")
                        .WithMany("Appointments")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_Status");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Appointments.DoctorAvailability", b =>
                {
                    b.HasOne("SGMC.Domain.Entities.Users.Doctor", "Doctor")
                        .WithMany("DoctorAvailabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DoctorAva__Docto__5535A963");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Insurance.InsuranceProvider", b =>
                {
                    b.HasOne("SGMC.Domain.Entities.Insurance.NetworkType", "NetworkType")
                        .WithMany("InsuranceProviders")
                        .HasForeignKey("NetworkTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_InsuranceProviders_NetworkType");

                    b.Navigation("NetworkType");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Medical.MedicalRecord", b =>
                {
                    b.HasOne("SGMC.Domain.Entities.Users.Doctor", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicalRecords_Doctor");

                    b.HasOne("SGMC.Domain.Entities.Users.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicalRecords_Patient");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.System.Notification", b =>
                {
                    b.HasOne("SGMC.Domain.Entities.Users.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__619B8048");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.Doctor", b =>
                {
                    b.HasOne("SGMC.Domain.Entities.Medical.AvailabilityMode", "AvailabilityMode")
                        .WithMany("Doctors")
                        .HasForeignKey("AvailabilityModeId")
                        .HasConstraintName("FK_Doctors_AvailabilityMode");

                    b.HasOne("SGMC.Domain.Entities.Users.Person", "DoctorNavigation")
                        .WithOne("Doctor")
                        .HasForeignKey("SGMC.Domain.Entities.Users.Doctor", "DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_Doctors_Person");

                    b.HasOne("SGMC.Domain.Entities.Medical.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .IsRequired()
                        .HasConstraintName("FK_Doctors_Speciality");

                    b.Navigation("AvailabilityMode");

                    b.Navigation("DoctorNavigation");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.Employee", b =>
                {
                    b.HasOne("SGMC.Domain.Entities.Users.Person", "EmployeeNavigation")
                        .WithOne("Employee")
                        .HasForeignKey("SGMC.Domain.Entities.Users.Employee", "EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Person");

                    b.Navigation("EmployeeNavigation");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.PasswordResetToken", b =>
                {
                    b.HasOne("SGMC.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.Patient", b =>
                {
                    b.HasOne("SGMC.Domain.Entities.Insurance.InsuranceProvider", "InsuranceProvider")
                        .WithMany("Patients")
                        .HasForeignKey("InsuranceProviderId")
                        .IsRequired()
                        .HasConstraintName("FK_Patients_InsuranceProvider");

                    b.HasOne("SGMC.Domain.Entities.Users.Person", "PatientNavigation")
                        .WithOne("Patient")
                        .HasForeignKey("SGMC.Domain.Entities.Users.Patient", "PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Patients_Person");

                    b.Navigation("InsuranceProvider");

                    b.Navigation("PatientNavigation");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.Person", b =>
                {
                    b.HasOne("SGMC.Domain.Entities.Users.User", "User")
                        .WithOne("UserNavigation")
                        .HasForeignKey("SGMC.Domain.Entities.Users.Person", "PersonId")
                        .IsRequired()
                        .HasConstraintName("FK_Persons_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("SGMC.Domain.Entities.System.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__RoleID__4316F928");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Insurance.InsuranceProvider", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Insurance.NetworkType", b =>
                {
                    b.Navigation("InsuranceProviders");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Medical.AvailabilityMode", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Medical.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.System.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.System.Status", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorAvailabilities");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.Person", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Employee");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SGMC.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("UserNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
